### ISSUE TITLE
Failed Downloading the Model

### ISSUE THREAD

**Issue by makamto** [breezedeus/Pix2Text-Mac#3]
When I try to test the result using "p2t predict -l en,ch_sim -a mfd -i assets/mixed-en.jpg", the terminal gave me this: RuntimeError: Failed downloading url https://sg-models.oss-cn-beijing.aliyuncs.com/cnstd/1.2/yolov7_tiny_mfd-pytorch.zip, and when I clicked it, the website gave:

Object.defineProperties(Navigator.prototype, { "globalPrivacyControl": { get: () => true, configurable: true, enumerable: true }, "doNotTrack": { get: () => true, configurable: true, enumerable: true }}); document.currentScript.parentElement.removeChild(document.currentScript); NoSuchBucket The specified bucket does not exist. 66229327A8F7503730529011 sg-models.oss-cn-beijing.aliyuncs.com sg-models 0015-00000101 https://api.aliyun.com/troubleshoot?q=0015-00000101

**Comment by breezedeus** [comment]
Refer to https://github.com/breezedeus/Pix2Text/issues/88#event-12509889763
