### ISSUE TITLE
Suggestion: We pre-select one of the OCR mode, and after we took a screenshot, the result is automatically copied. 

### ISSUE THREAD

**Issue by makamto** [breezedeus/Pix2Text-Mac#4]
Here is the workflow:

1. If we only want to use Mixed OCR, then there is a setting for making it to be default mode,
2. After we set Mixed OCR as default mode,
3. If we took a screenshot, the result is also automatically copied to clipboard.

Pros:

- It can boost productivity, and do the operation without clicking the menu bar icon to select the mode.

**Comment by breezedeus** [comment]
Thanks for the suggestion. However, this operation needs to set a specific shortcut key or it will recognize all the screenshot images in the clipboard. I don't know how to set specific shortcuts yet 😅.

**Comment by horennel** [comment]
很早以前就实现了，@breezedeus，用这个代码改就行，没有用到快捷键，用轮询实现的。https://github.com/horennel/LaTex-OCR_for_macOS
